export const DATA = {
  labelFileName: "File Name",
  labelFileType: "File Type",
  labelLastModified: "Last Modified",
  msgChooseFile: "Please choose file before pressing the Upload button",
  msgUploading: "Please wait while file is being uploaded",
  msgUpload: "Upload donor's file",
  msgAddPatient: "Add Patient's details",
  msgPatients: "Patient's list",
  msgDonations: "Close Donation Requests",
  msgError: "Error occured so please try again.",
  btnUpload: "Upload!",
  navUpload: "Upload Donors",
  navAddPatient: "Add Patient",
  navBrand: "Saving Lives",
  navPatients: "Patients list",
  navDonation: "Plasma Request",
  footerContactUs: "Contact Us",
  footerAboutUs: "About Us",
};
